// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://floqamemnppohwprnneh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsb3FhbWVtbnBwb2h3cHJubmVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDY3MzIsImV4cCI6MjA2ODU4MjczMn0.tr5wGyJ3ScCkftMXDrsQgQp16rSVjJLfK31a-dNSx-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});